name: games-action

on:
  schedule:
    - cron: 0 19 * * *

jobs:
  fetch-games:
    name: Fetch Games
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
      - run: npm run fetch-games
